apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
        containers:
        - name: user-service
          image: kaansari/user-service:latest
          imagePullPolicy: Always
          command: [
            "./user-service",
            "--selector=static",
            "--server_address=:50051"
          ]
          env:
          - name: DB_HOST
            value: "postgre-db-svc.db"
          - name: DB_NAME
            value: "flexdeploy"
          - name: DB_PASSWORD
            value: "c67"
          - name: DB_USER
            value: "creator"
          - name: UPDATED_AT
            value: "Wed Jan 20 15:17:44 EST 2021"
          ports:
          - containerPort: 50051
            name: user-port
